spring:
  cloud:
    config:
      enabled: false
  data:
    mongodb:
      database: usersCashing
  application.name: cashing

logging:
  config: "classpath:logback-spring.xml"
  file: logs/cashing

